import { Header } from "@/components/core/header";
import { Viewport } from "@/components/core/viewport";

export default function Page() {
    return (
        <>
            <Header title="Video" />
            <Viewport>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
                <p>Video</p>
            </Viewport>
        </>
    );
}
